apiVersion: v1
kind: Namespace
metadata:
  name: lab-mesh
  labels:
    environment: evaluation-lab
    mesh-dataplane: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-edge
  labels:
    environment: evaluation-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: attacker
  labels:
    environment: unauthenticated-zone
    security.policy: untrusted
